### ISSUE TITLE
Compiling with code optimization throws NullReferenceException

### ISSUE THREAD

**Issue by marcells** [vescon/MethodBoundaryAspect.Fody#3] opened 2016-01-14 13:34 UTC
This method throws a NullReferenceException (`someObject` is never null), when it is compiled with **code optimization** (default Release configuration).

```
enum SomeEnum { Test1, Test2 };
abstract class SomeBaseObject { }
class SomeObject1 : SomeBaseObject { }
class SomeObject2 : SomeBaseObject { }

private static SomeEnum SomeMethod(SomeBaseObject someObject)
{
    if (someObject is SomeObject1)
        return SomeEnum.Test1;

    if (someObject is SomeObject2)
        return SomeEnum.Test2;

    throw new InvalidOperationException();
}
```

**Comment by Ralf1108** [comment] 2016-02-08 17:24
can not reproduce this issue currently ...need more info/ test scenario

**Comment by marceloconte** [comment] 2017-06-22 15:33
Hi, first of all, great job you`re doing!  I just switched from postsharp and found out that every thing went very smooth, untill I`ve deploied with a custom transformation config copieng from debug or release configs didn`t matter, I got the error mentioned. I suppose the problem is related with the extension only compiling 'obj/debug' and not 'obj/release' or other custom locations. I changed config of debug configuration to optimization and 'advanced/pdb_only' and it work just fine. I hope I shed a light at the problem that would help me a lot to have solved ;)

**Comment by SparkRooster** [comment] 2017-12-12 07:40
I have the same problem, in Release mode there is a NullReferenceException in some methods where an attribute overriding OnMethodBoundaryAspect

**Comment by SparkRooster** [comment] 2017-12-12 11:02
I have a reproducable. The following will in Release or Debug mode with Optimize code flag on, throw a NullReferenceException when called:

[WebMethodLogTracking]
public string Method(int number)
{
	switch (number)
	{
		case 1:
			return "Apa";
		case 2:
			return "bepa";
		default:
			throw new ApplicationException();
	}
}

where is an OnMethodBoundaryAspect override.
The following is a decompilation of the method:
[WebMethodLogTracking]
    public string Method(int number)
    {
      object[] objArray = new object[1]{ (object) number };
      MethodExecutionArgs args1 = new MethodExecutionArgs();
      args1.Arguments = objArray;
      MethodBase currentMethod1 = MethodBase.GetCurrentMethod();
      args1.Method = currentMethod1;
      object obj1 = (object) this;
      args1.Instance = obj1;
      new WebMethodLogTracking().OnEntry(args1);
      MethodExecutionArgs args2 = new MethodExecutionArgs();
      args2.Arguments = objArray;
      MethodBase currentMethod2 = MethodBase.GetCurrentMethod();
      args2.Method = currentMethod2;
      object obj2 = (object) this;
      args2.Instance = obj2;
      new WebMethodLogTracking().OnEntry(args2);
      string str;
      if (number != 1)
      {
        if (number != 2)
          throw (Exception) new ApplicationException();
        str = "bepa";
      }
      else
        str = "Apa";
      Exception exception;
      throw exception;
    }

**Comment by Ralf1108** [comment] 2017-12-22 13:55
@SparkRooster can you post the code of your aspect "WebMethodLogTracking" ?

**Comment by Ralf1108** [comment] 2017-12-22 15:18
Problem was special handling of methods when they end with "throw" opcode.
The code with this switch or similar if statements produces il code which looks like they end with a "throw" but really have multiple return opcodes in between.

![grafik](https://user-images.githubusercontent.com/3949137/34302914-66254044-e733-11e7-8dc8-3f1e6d2781a6.png)


This caused the weaved code to duplicate the throw opcode at the end:
![grafik](https://user-images.githubusercontent.com/3949137/34302950-8be7b424-e733-11e7-944b-cff7216c53cf.png)


The last throw should be in this case just a "ret" opcode.
![grafik](https://user-images.githubusercontent.com/3949137/34302975-ac51ef04-e733-11e7-97d0-b8c2c1dc033e.png)


Bug could be reproduced and is fixed now.
I still have to upload an updated nuget package.

**Closed** 2017-12-22 15:19 UTC
Labels: bug
